# Generated by Django 5.0.3 on 2024-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroMat', models.CharField(max_length=100, unique=True)),
                ('modulecar', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
