# Generated by Django 5.0.3 on 2024-04-08 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleVoiture",
            fields=[
                ("id_module", models.AutoField(primary_key=True, serialize=False)),
                ("name_module", models.CharField(max_length=255)),
                ("marque", models.CharField(max_length=63, null=True)),
                ("puissance", models.IntegerField(null=True)),
                ("nbr_place", models.IntegerField(null=True)),
                ("reservoir", models.IntegerField(null=True)),
                ("prix_neuf", models.IntegerField(null=True)),
                ("etat", models.CharField(default="neuf", max_length=5, null=True)),
                ("desponiblte", models.CharField(max_length=55, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="voiture",
            name="couleur",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="voiture",
            name="modulecar",
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="voiture",
            name="numeroMat",
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="voiture",
            name="type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="agent",
            fields=[
                ("id_agent", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=127)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("numerotel", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id_client", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=127)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("numerotel", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="voiture",
            name="modulevoiture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboardapp.modulevoiture",
            ),
        ),
        migrations.CreateModel(
            name="reservation",
            fields=[
                (
                    "id_reservation",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("date_reservation", models.DateField(blank=True, null=True)),
                ("numero_tel", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboardapp.client",
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboardapp.voiture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sous_traitance",
            fields=[
                (
                    "id_sous_traitance",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("taux_echeance", models.IntegerField(blank=True, null=True)),
                ("number_echeance", models.IntegerField(null=True)),
                ("number_echance_paier", models.IntegerField(null=True)),
                ("avance", models.IntegerField(null=True)),
                ("date_paiment", models.DateField(blank=True, null=True)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboardapp.agent",
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboardapp.voiture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="historique_st",
            fields=[
                ("id_echeance", models.AutoField(primary_key=True, serialize=False)),
                ("echeance", models.IntegerField(null=True)),
                ("date_paiment", models.DateField(blank=True, null=True)),
                ("staut", models.CharField(blank=True, max_length=55, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "voiture",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboardapp.voiture",
                    ),
                ),
                (
                    "sous_traitance",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboardapp.sous_traitance",
                    ),
                ),
            ],
        ),
    ]
