# Generated by Django 5.0.3 on 2024-04-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0002_modulevoiture_alter_voiture_couleur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="marquevehicule",
            fields=[
                ("id_marque", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="modulevoiture",
            name="marque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboardapp.marquevehicule",
            ),
        ),
    ]
