# Generated by Django 5.0.3 on 2024-04-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0003_marquevehicule_alter_modulevoiture_marque"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voiture",
            name="modulecar",
        ),
        migrations.AlterField(
            model_name="voiture",
            name="type",
            field=models.CharField(max_length=63, null=True),
        ),
    ]
