# Generated by Django 5.0.3 on 2024-04-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0004_remove_voiture_modulecar_alter_voiture_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voiture",
            name="type",
        ),
        migrations.AddField(
            model_name="modulevoiture",
            name="type",
            field=models.CharField(max_length=63, null=True),
        ),
    ]
