# Generated by Django 5.0.3 on 2024-04-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0007_modulevoiture_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prices",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField(null=True)),
                (
                    "module",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboardapp.modulevoiture",
                    ),
                ),
            ],
        ),
    ]
