# Generated by Django 5.0.3 on 2024-04-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0008_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiture",
            name="status",
            field=models.CharField(default="nouveau", max_length=255, null=True),
        ),
    ]
