# Generated by Django 5.0.3 on 2024-04-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0010_alter_reservation_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiture",
            name="agent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboardapp.agent",
            ),
        ),
    ]
