# Generated by Django 5.0.3 on 2024-03-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarapp', '0002_remove_voiture_statutvoiture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
